package com.example.trafykamerasikotlin.data.update

import android.util.Base64
import android.util.Log
import com.google.crypto.tink.subtle.Ed25519Verify
import org.json.JSONObject

/**
 * Verifies the ed25519 signature on `update.json` against the embedded production
 * public key. The public key is the 32 raw bytes produced by
 * `scripts/generate-apk-signing-key.js` on the server — NOT SPKI/ASN.1-wrapped.
 *
 * Verification flow:
 *  1. Parse the manifest.
 *  2. Pull out & base64-decode the `signature` field.
 *  3. Remove `signature` from the object.
 *  4. Canonicalize the remaining fields with [CanonicalJson].
 *  5. Ed25519Verify(pubkey).verify(sigBytes, canonicalBytes).
 *
 * Any failure (missing field, malformed base64, invalid signature) → returns false.
 * Never falls back to "trust anyway" — an unsigned manifest must be rejected loudly,
 * otherwise the whole signing scheme is pointless.
 */
object ManifestVerifier {

    private const val TAG = "Trafy.ManifestVerify"

    /**
     * Production ed25519 public key (32 raw bytes, standard base64).
     * Generated by scripts/generate-apk-signing-key.js on the Oweb VPS.
     */
    private const val PUBLIC_KEY_B64 = "kxlWdxBAtnkApChfK/PifgozKzSm3oHU5UK0U3wr+yo="

    private val publicKeyBytes: ByteArray by lazy {
        Base64.decode(PUBLIC_KEY_B64, Base64.NO_WRAP)
    }

    /**
     * Verifies [manifestJson] in place (mutates a local parse — does not touch the caller's
     * string). On success, returns the parsed object with the `signature` field removed.
     * On any failure, returns null.
     */
    fun verify(manifestJson: String): JSONObject? {
        val obj = try {
            JSONObject(manifestJson)
        } catch (e: Exception) {
            Log.w(TAG, "manifest parse failed: ${e.message}")
            return null
        }

        val sigB64 = obj.optString("signature", "")
        if (sigB64.isBlank()) {
            Log.w(TAG, "manifest missing 'signature' field")
            return null
        }

        val sigBytes = try {
            Base64.decode(sigB64, Base64.NO_WRAP)
        } catch (e: Exception) {
            Log.w(TAG, "signature base64 decode failed: ${e.message}")
            return null
        }

        obj.remove("signature")

        val canonical = try {
            CanonicalJson.canonicalize(obj)
        } catch (e: Exception) {
            Log.w(TAG, "canonicalize failed: ${e.message}")
            return null
        }

        return try {
            Ed25519Verify(publicKeyBytes).verify(sigBytes, canonical)
            obj
        } catch (e: Exception) {
            Log.w(TAG, "ed25519 verify failed: ${e.javaClass.simpleName}: ${e.message}")
            null
        }
    }
}
